export const projects = [
	// {
	// 	title: 'Teslo Shop',
	// 	description: 'tesloShop',
	// 	stack: ['Next.Js', 'Node.Js', 'MongoDB', 'Docker'],
	// 	demoUrl: 'https://teslo-shop-topaz.vercel.app/',
	// 	codeUrl: 'https://github.com/Curso-NextJs/teslo-shop',
	// 	imageUrl: '/images/projects/teslo-shop.jpg',
	// },
	{
		title: "Thrullo",
		description: "thrullo",
		stack: ["TypeScript", "Next.Js", "TailwindCSS", "Supabase"],
		demoUrl: "https://thrullo.vercel.app/",
		codeUrl: "https://github.com/iancarlosortega/thrullo",
		imageUrl: "/images/projects/thrullo.png",
	},
	{
		title: "FreeMove",
		description: "freeMove",
		stack: ["Angular", "Firebase", "Mapbox"],
		demoUrl: "https://freemove-aa0c5.web.app/",
		codeUrl: "https://github.com/iancarlosortega/freeMove",
		imageUrl: "/images/projects/freemove.png",
	},
	{
		title: "Chat Group - Realtime",
		description: "chatGroup",
		stack: ["TypeScript", "Next.Js", "NestJS", "Docker", "Postgresql"],
		demoUrl: "https://chat-group-phi.vercel.app/",
		codeUrl: "https://github.com/iancarlosortega/chat-group",
		imageUrl: "/images/projects/chat-group.png",
	},
	{
		title: "Shoppingify",
		description: "shoppingify",
		stack: ["TypeScript", "Next.Js", "TailwindCSS", "Supabase"],
		demoUrl: "https://shoppingify-blond.vercel.app/",
		codeUrl: "https://github.com/iancarlosortega/shoppingify",
		imageUrl: "/images/projects/shoppingify.png",
	},
	{
		title: "Arch Studio",
		description: "archStudio",
		stack: ["Astro", "React", "TailwindCSS"],
		demoUrl: "https://arch-studio-iota.vercel.app/",
		codeUrl: "https://github.com/iancarlosortega/astro-studio",
		imageUrl: "/images/projects/arch-studio.jpg",
	},
	{
		title: "UTPL Play",
		description: "utplPlay",
		stack: ["Angular", "Firebase"],
		demoUrl: "https://play.liidutpl.ec/",
		codeUrl: "https://github.com/iancarlosortega/utplPlay",
		imageUrl: "/images/projects/utpl-play.png",
	},
	{
		title: "Creando Cariño",
		description: "creandoCarino",
		stack: ["Angular", "Firebase"],
		demoUrl: "https://creando-carino.web.app/",
		codeUrl: "https://github.com/iancarlosortega/creandoCarino",
		imageUrl: "/images/projects/creando-carino.jpg",
	},
];
