export const projects = [
	{
		title: "Sara",
		description: "sara",
		stack: ["TypeScript", "React", "TailwindCSS", "Next.Js"],
		demoUrl: "https://sara.ciat.org/public/library",
		imageUrl: "/images/projects/sara.png",
		features: ["saraFeature1", "saraFeature2", "saraFeature3", "saraFeature4"],
		imageCount: 13,
	},
	{
		title: "Stowlog",
		description: "stowlog",
		stack: ["TypeScript", "NestJS", "MongoDB", "Redis"],
		demoUrl: "https://www.stowlog.com/",
		imageUrl: "/images/projects/stowlog.png",
		features: [
			"stowlogFeature1",
			"stowlogFeature2",
			"stowlogFeature3",
			"stowlogFeature4",
		],
		imageCount: 7,
	},
	// {
	// 	title: "Inproalimentos",
	// 	description: "inproalimentos",
	// 	stack: [
	// 		"TypeScript",
	// 		"Next.Js",
	// 		"TailwindCSS",
	// 		"Expo",
	// 		"NestJS",
	// 		"PostgreSQL",
	// 	],
	// 	demoUrl: "https://sara.ciat.org",
	// 	imageUrl: "/images/projects/sara.png",
	// 	features: [
	// 		"inproalimentosFeature1",
	// 		"inproalimentosFeature2",
	// 		"inproalimentosFeature3",
	// 		"inproalimentosFeature4",
	// 	],
	// 	imageCount: 5,
	// },
	{
		title: "Thrullo",
		description: "thrullo",
		stack: ["TypeScript", "Next.Js", "TailwindCSS", "Supabase"],
		demoUrl: "https://thrullo.vercel.app/",
		codeUrl: "https://github.com/iancarlosortega/thrullo",
		imageUrl: "/images/projects/thrullo.png",
		features: [
			"thrulloFeature1",
			"thrulloFeature2",
			"thrulloFeature3",
			"thrulloFeature4",
		],
		imageCount: 5,
	},
	{
		title: "FreeMove",
		description: "freeMove",
		stack: ["Angular", "Firebase", "Mapbox"],
		demoUrl: "https://freemove-aa0c5.web.app/",
		codeUrl: "https://github.com/iancarlosortega/freeMove",
		imageUrl: "/images/projects/freemove.png",
		features: [
			"freeMoveFeature1",
			"freeMoveFeature2",
			"freeMoveFeature3",
			"freeMoveFeature4",
		],
		imageCount: 5,
	},
	{
		title: "Arch Studio",
		description: "archStudio",
		stack: ["Astro", "React", "TailwindCSS"],
		demoUrl: "https://arch-studio-iota.vercel.app/",
		codeUrl: "https://github.com/iancarlosortega/astro-studio",
		imageUrl: "/images/projects/arch-studio.jpg",
		features: [
			"archStudioFeature1",
			"archStudioFeature2",
			"archStudioFeature3",
			"archStudioFeature4",
		],
		imageCount: 5,
	},
	{
		title: "Shoppingify",
		description: "shoppingify",
		stack: ["TypeScript", "Next.Js", "TailwindCSS", "Supabase"],
		demoUrl: "https://shoppingify-blond.vercel.app/",
		codeUrl: "https://github.com/iancarlosortega/shoppingify",
		imageUrl: "/images/projects/shoppingify.png",
		features: [
			"shoppingifyFeature1",
			"shoppingifyFeature2",
			"shoppingifyFeature3",
			"shoppingifyFeature4",
		],
		imageCount: 5,
	},

	{
		title: "Creando Cariño",
		description: "creandoCarino",
		stack: ["Angular", "Firebase"],
		demoUrl: "https://creando-carino.web.app/",
		codeUrl: "https://github.com/iancarlosortega/creandoCarino",
		imageUrl: "/images/projects/creando-carino.jpg",
		features: [
			"creandoCarinoFeature1",
			"creandoCarinoFeature2",
			"creandoCarinoFeature3",
			"creandoCarinoFeature4",
		],
		imageCount: 5,
	},
	{
		title: "UTPL Play",
		description: "utplPlay",
		stack: ["Angular", "Firebase"],
		demoUrl: "https://play.liidutpl.ec/",
		codeUrl: "https://github.com/iancarlosortega/utplPlay",
		imageUrl: "/images/projects/utpl-play.png",
		features: [
			"utplPlayFeature1",
			"utplPlayFeature2",
			"utplPlayFeature3",
			"utplPlayFeature4",
		],
		imageCount: 5,
	},

	{
		title: "Chat Group - Realtime",
		description: "chatGroup",
		stack: ["TypeScript", "Next.Js", "NestJS", "Docker", "Postgresql"],
		demoUrl: "https://chat-group-phi.vercel.app/",
		codeUrl: "https://github.com/iancarlosortega/chat-group",
		imageUrl: "/images/projects/chat-group.png",
		features: [
			"chatGroupFeature1",
			"chatGroupFeature2",
			"chatGroupFeature3",
			"chatGroupFeature4",
		],
		imageCount: 5,
	},
];
